docs: include authentication example to examples page
goetzrobin/spartan pull request #256
Opened 2024-04-08 21:14 UTC by danilolmc

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

The current examples page has very few examples showing what can be done using the spartan/ui library

Closes #241 

## What is the new behavior?

The examples page now gets an authentication example showcasing
what can be done with spartan/ui, this is a starting point to add more examples to the page similar to shadcn/ui

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2024-04-25 14:12 UTC, goetzrobin requested changes
Some minor changes! Thanks for all your work!

2024-04-25 14:12 UTC, goetzrobin commented on apps/app/src/app/pages/(examples)/examples/authentication/(authentication).page.ts
> +			<div class="md:hidden">
Let's create a responsive version of this screen and remove the shadcn images

2024-04-25 14:12 UTC, goetzrobin commented on apps/app/src/app/pages/(examples)/examples/authentication/(authentication).page.ts
> +					class="focus-visible:ring-ring hover:bg-accent absolute right-4 top-4 inline-flex h-9 items-center justify-center whitespace-nowrap rounded-md px-4 py-2 text-sm font-medium  transition-colors ho
You shouldn't need that many extra classes when using the hlmBtn directive

2024-04-25 14:12 UTC, goetzrobin commented on apps/app/src/app/pages/(examples)/examples/authentication/components/form.component.ts
> +								class="sr-only text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
Can we use hlmLabel for this?

2024-04-25 14:12 UTC, goetzrobin commented on apps/app/src/app/pages/(examples)/examples/authentication/components/form.component.ts
> +								class="flex h-9 w-full focus-visible:ring-1"
Do we need these even with the hlmInput?

2024-04-25 14:12 UTC, goetzrobin commented on apps/app/src/app/pages/(examples)/examples/authentication/components/form.component.ts
> +							animate-spin
animate-spin is normally a class that's added to the icon. I think we can remove it here

2024-06-01 22:51 UTC, thatsamsonkid commented
Hi @danilolmc sorry I know this has been sitting for a while, was curious if you could rebase the branch so at least the checks can run again. I think you resolved all the previous comments so I'd be happy to see to getting this merged in

2024-06-03 15:19 UTC, danilolmc commented
Hi @thatsamsonkid, no problem, I'm going to rebase the branch.

2024-06-03 15:30 UTC, danilolmc commented
It's done @thatsamsonkid !

2024-06-03 17:04 UTC, thatsamsonkid commented on apps/app/src/app/pages/(examples)/examples/authentication/(authentication).page.ts
> +import { metaWith } from '~/app/shared/meta/meta.util';
@danilolmc - this tilde seems to be causing the build to fail, I think this just needs to be updated to "@spartan-ng/app/shared/meta/meta.util" instead.

2024-06-04 00:25 UTC, danilolmc commented
Thanks for your review @thatsamsonkid!

Now it's resolved!

2024-06-04 12:15 UTC, merged