feat(input): ngcontrol error input test
goetzrobin/spartan pull request #37
Opened 2023-10-20 21:46 UTC by okkindel

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Feature

## Which package are you modifying?

- [x] input

## What is the current behavior?

I was wondering about integrating Input with Reactive Forms when it comes to presenting the error state - in my opinion, since the library is being created for Angular, it is worth considering. I am presenting the initial concept, you can safely ignore it if you don't like it, it is basically not so much a ready PR as a POC solution - maybe it's just worth discussing. See if you see such a solution in your project.

## What is the new behavior?

Input for the `error` state and integration with NgControl which allows for self-management of the components error state.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2023-10-23 20:13 UTC, okkindel commented
Actually, classes are a better idea, I don't know why I didn't think of it - we get rid of a whole lot of code. I like this much more, I would make one change, with errorAware we can only control whether the control should react to `its' errors, but we cannot force this error from the outside, which may be useful for people who do not use ReactiveForms or want to make the state dependent from other variables, so I would introduce a slightly different implementation:

```
error: {
  auto: '[.ng-invalid]:text-destructive [.ng-invalid]:border-destructive [.ng-invalid]:focus-visible:ring-destructive',
  true: 'text-destructive border-destructive focus-visible:ring-destructive',
},

....

defaultVariants: {
  [...]
  error: 'auto',
},
```

Additionally, we should react to ng-invalid and ng-touched at the same time, because we don't want to see an error before we start entering data on an empty form with required controls.

However, I don't know how to create these conditional statements, because the method you provided will not work, this way of writing conditions works for groups: https://tailwindcss.com/docs/hover-focus-and-other-states#arbitrary-groups, but not for `host`.

2023-10-23 20:27 UTC, okkindel commented
I've updated the code - let me know what you think.

2023-10-23 20:38 UTC, goetzrobin commented
I like it! I think this is absolutely going into the right direction.
This might be another PR, but I think we could use the same approach to the label.
And add something like this:
```
[&:has([hlmInput].ng-invalid.ng-touched)]:text-destructive [&:has([hlmInput].ng-invalid.ng-touched)]:text-destructive
```

One thing, could you add a story that uses ngModel?

2023-10-23 20:39 UTC, goetzrobin commented
We might also want to add a "false" variant doing nothing

2023-10-23 20:42 UTC, okkindel commented
We have false by default: 
![image](https://github.com/goetzrobin/spartan/assets/3685425/83fc47d3-8ca3-45e9-bebb-0171ac8855cd)

2023-10-23 20:57 UTC, okkindel commented
I added changes to the storybook

2023-10-23 21:10 UTC, okkindel commented
I also added variant for labels - in a similar style

2023-10-25 18:42 UTC, goetzrobin requested changes
Two minor changes! Rest looks great! Thanks for adding this!

2023-10-25 18:42 UTC, goetzrobin commented on libs/ui/input/helm/src/lib/hlm-input.directive.ts
> +        auto: '[&.ng-invalid&.ng-touched]:text-destructive [&.ng-invalid&.ng-touched]:border-destructive [&.ng-invalid&.ng-touched]:focus-visible:ring-destructive',
```suggestion
        auto: '[&.ng-invalid.ng-touched]:text-destructive [&.ng-invalid.ng-touched]:border-destructive [&.ng-invalid.ng-touched]:focus-visible:ring-destructive',
```
Same here

2023-10-25 19:25 UTC, okkindel commented on libs/nx/src/generators/ui/libs/ui-input-helm/files/lib/hlm-input.directive.ts.template
> +        auto: '[&.ng-invalid&.ng-touched]:text-destructive [&.ng-invalid&.ng-touched]:border-destructive [&.ng-invalid&.ng-touched]:focus-visible:ring-destructive',
It is IMO, i was testing it, we are catching `host` classes.

2023-10-25 20:54 UTC, goetzrobin approved these changes

2023-10-25 20:55 UTC, merged